config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /ru|en/ do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    devise_scope :user do
      get 'registration', to: 'devise/registrations#new', as: :new_user_registration
    end
    devise_for :users

    resources :posts do
      get '/page/:page', action: :index, on: :collection
      resources :comments
    end
    resources :tags

    get '/access_denied', to: 'home#access_deny', as: :access_denied

    root 'posts#index'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :user

  has_one_attached :image
  after_commit :add_default_image, on: %i[update]

  paginates_per 15

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :content, presence: true, length: { minimum: 20 }
  validates :image, content_type: ['image/png', 'image/jpeg', 'image/jpg']

  def tag_list
    tags.collect(&:name).join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name:) }
    self.tags = new_or_found_tags
  end

  def image_as_thumbnail
    if image.attached?
      image
    else
      'Spanish.jpg'
    end
  end

  private

  def add_default_image
    return if image.attached?

    image.attach(
      io: File.open(Rails.root.join('app', 'assets', 'images', 'Spanish.jpg')),
      filename: 'Spanish.jpg',
      content_type: 'image/jpg'
    )
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do
    redirect_to(access_denied_path)
  end

  def default_url_options
    { locale: I18n.locale }
  end

  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale] = I18n.locale
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]

    @comment.save

    redirect_to post_path(@comment.post)
  end

  def comment_params
    params.require(:comment).permit(:user_id, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def access_deny
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    if user_signed_in? && params[:user_id]
      @posts = Post.where(user_id: params[:user_id]).order(created_at: :desc).page params[:page]
    else
      @posts = Post.order(created_at: :desc).page params[:page]
    end
  end

  def show
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  def new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def current_ability
    @current_ability ||= PostAbility.new(current_user)
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :image, :tag_list)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link(path)
    if current_page?(path)
      'bg-green-700 text-white'
    else
      'bg-green-600 text-gray-100'
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_registration_error_messages
    flash.now[:registration_errors] = resource.errors.full_messages if resource.errors.any?
  end
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </p>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <p>
    <%= f.submit class: 'my-5 py-2.5 px-5 border border-transparent text-md md:text-sm leading-5 text-center font-medium rounded-md text-white bg-green-600 hover:bg-green-500 focus:outline-none focus:border-green-700 focus:shadow-outline-green active:bg-green-700 transition duration-150 ease-in-out' %>
  </p>
<% end %>

app/views/home/access_deny.html.erb
<svg style="display: none;">
  <symbol id="keyhole" xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 26.458333 26.458334"><g transform="translate(0 -270.542)"><circle cx="13.229" cy="279.141" r="8.599" fill="#f1eedb" paint-order="stroke fill markers" /><path d="M10.516 283.271h5.427c1.164 0 1.768.861 2.102 1.802l3.59 10.125c.334.94-.937 1.802-2.102 1.802H6.926c-1.165 0-2.437-.861-2.103-1.802l3.59-10.125c.334-.94.938-1.802 2.103-1.802z" fill="#f1eedb" paint-order="stroke fill markers" /><circle r="6.06" cy="279.141" cx="13.229" fill="#282b24" paint-order="stroke fill markers" /><path d="M11.502 283.76h3.455c.741 0 1.126.733 1.338 1.534l2.286 8.614c.213.8-.597 1.534-1.338 1.534H9.216c-.742 0-1.551-.733-1.339-1.534l2.286-8.614c.212-.8.597-1.534 1.339-1.534z" fill="#282b24" paint-order="stroke fill markers" /></g></symbol>
  <symbol id="key" xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 26.458333 26.458334"><circle cx="13.229" cy="279.141" r="8.599" paint-order="stroke fill markers" transform="matrix(0 -.76923 .7499 0 -202.882 23.405)" fill="#f1eedb" /><circle r="8.599" cy="279.141" cx="13.229" paint-order="stroke fill markers" transform="matrix(0 -.5887 .57392 0 -153.756 21.017)" fill="#282b24" /><path fill="#f1eedb" paint-order="stroke fill markers" d="M12.03 12.13h14.428v2.2H12.03z" /><path fill="#f1eedb" paint-order="stroke fill markers" d="M18.147 12.13h2.895v6.772h-2.895zM22.113 12.13h2.716v5.065h-2.716z" /></symbol>
  <symbol id="ghost" xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 26.458333 26.458334"><g transform="translate(0 -270.542)"><path d="M4.63 279.293c0-4.833 3.85-8.751 8.6-8.751 4.748 0 8.598 3.918 8.598 8.75H13.23zM4.725 279.293h16.914c.052 0 .19.043.19.096l-.095 14.329c0 .026-.011.05-.028.068a.093.093 0 0 1-.067.028c-.881 0-1.235-1.68-2.114-1.616-.995.072-1.12 2.082-2.114 2.154-.88.064-1.233-1.615-2.115-1.615-.881 0-1.233 1.615-2.114 1.615-.881 0-1.233-1.615-2.114-1.615-.882 0-1.236 1.679-2.115 1.615-.994-.072-1.12-2.082-2.114-2.154-.88-.063-1.41 1.077-2.114 1.616-.021.016-.05-.01-.067-.028a.097.097 0 0 1-.028-.068v-14.33c0-.052.042-.095.095-.095z" fill="#f1eedb" paint-order="stroke fill markers" /><path d="M15.453 281.27a1.987 1.94 0 0 1-.994 1.68 1.987 1.94 0 0 1-1.987 0 1.987 1.94 0 0 1-.994-1.68h1.988z" fill="#282b24" paint-order="stroke fill markers" /><g fill="#282b24" transform="matrix(1 0 0 1.0177 .283 -5.653)"><ellipse cx="10.205" cy="278.668" rx="1.231" ry="1.181" paint-order="stroke fill markers" /><ellipse ry="1.181" rx="1.231" cy="278.668" cx="16.159" paint-order="stroke fill markers" /><ellipse ry=".331" rx=".853" cy="280.936" cx="10.205" opacity=".5" paint-order="stroke fill markers" /><ellipse cx="16.159" cy="280.936" rx=".853" ry=".331" opacity=".5" paint-order="stroke fill markers" /></g><ellipse ry=".614" rx="8.082" cy="296.386" cx="13.229" opacity=".1" fill="#f1eedb" paint-order="stroke fill markers" /></g></symbol>
</svg>

<div class="container">
  <h1>403</h1>
  <p>access not granted</p>
  <svg class="keyhole">
    <use href="#keyhole" />
  </svg>
</div>

<svg class="key">
  <use href="#key" />
</svg>

<div class="ghost">
  <svg class="ghost">
    <use href="#ghost" />
  </svg>
</div>

<style>
@import url('https://fonts.googleapis.com/css?family=Open+Sans|Nova+Mono');
:root {
  --font-header: 'Nova Mono', monospace;
  --font-text: 'Open Sans', sans-serif;
  --color-theme: #F1EEDB;
  --color-bg: #282B24;

  --animation-sentence: 'You know you\'re supposed to leave, right?';
  --animation-duration: 40s;
}
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
body {
  width: 100%;
  font-family: var(--font-text);
  color: var(--color-theme);
  background: var(--color-bg);
  overflow: hidden;
}
.container {
  text-align: center;
  margin: 1rem 0.5rem 0;
}
.container h1 {
  font-family: var(--font-header);
  font-size: calc(4rem + 2vw);
  text-transform: uppercase;
}
.container p {
  text-transform: uppercase;
  letter-spacing: 0.2rem;
  font-size: 2rem;
  margin: 1.5rem 0 3rem;
}
svg.keyhole {
  height: 82px;
  width: 82px;
  opacity: 0;
  visibility: hidden;
  animation: showKey 0.5s 0.5s paused ease-out forwards;
}
svg.key {
  height: 164px;
  width: 164px;
  position: absolute;
  opacity: 0;
  visibility: hidden;
  animation: showKey 0.5s 0.5s paused ease-out forwards;
}
.ghost {
  position: absolute;
  bottom: 5px;
  left: calc(50% - 100px);
  width: 200px;
  height: 200px;
  animation: hoverGhost calc(var(--animation-duration)/2) ease-in-out 2;
}
.ghost:before {
  content: var(--animation-sentence);
  color: var(--color-theme);
  border-radius: 50%;
  position: absolute;
  bottom: 100%;
  text-align: center;
  line-height: 2;
  padding: 1rem;
  visibility: hidden;
  opacity: 0;
  animation:
    showText calc(var(--animation-duration)/8) calc(var(--animation-duration)*3/16) ease-out forwards,
    showNewText calc(var(--animation-duration)/8) calc(var(--animation-duration)*27/40) ease-out forwards,
    showFinalText calc(var(--animation-duration)/8) var(--animation-duration) ease-out forwards;
}

@keyframes hoverGhost {
  25% {
    transform: translateX(20vw);
  }
  75% {
    transform: translateX(-20vw);
  }
}

@keyframes showKey {
  to {
    opacity: 1;
    visibility: visible;
  }
}

@keyframes showText {
  2% {
    opacity: 1;
    visibility: visible;
  }
  98% {

    opacity: 1;
    visibility: visible;
  }
  99% {
    --animation-sentence: 'You know you\'re supposed to leave, right?';
    opacity: 0;
    visibility: hidden;
  }
  100% {
    --animation-sentence: 'So much to do, so little time...';
  }
}
@keyframes showNewText {
  2% {
    --animation-sentence: 'So much to do, so little time...';
    opacity: 1;
    visibility: visible;
  }
  98% {

    opacity: 1;
    visibility: visible;
  }
  99% {
    --animation-sentence: 'So much to do, so little time...';
    opacity: 0;
    visibility: hidden;
  }
  100% {
    --animation-sentence: 'Okay, you seem to care about this. Here\'s a key just for you';
  }
}
@keyframes showFinalText {
  2% {
    opacity: 1;
    visibility: visible;
  }
  98% {
    opacity: 1;
    visibility: visible;
  }
  100% {
    opacity: 0;
    visibility: hidden;
  }
}
</style>

<script>
const key = document.querySelector(".key");
const keyhole = document.querySelector(".keyhole");
const ghost = document.querySelector(".ghost");

const heading = document.querySelector("h1");
const paragraph = document.querySelector("p");

const root = document.querySelector(":root");
const rootStyles = getComputedStyle(root);
const animationDuration = parseInt(rootStyles.getPropertyValue("--animation-duration"))*1000;
let keyTimer = animationDuration*9/8;

const keyBox = key.getBoundingClientRect();
const timeoutID = setTimeout(() => {
  key.parentElement.parentElement.style.cursor = "grab";

  key.style.animationPlayState = "running";
  keyhole.style.animationPlayState = "running";

  key.style.pointerEvents = "none";

  window.addEventListener("mousemove", updateKeyPosition);

  keyhole.addEventListener("mouseover", grantAccess);

  clearTimeout(timeoutID);
}, keyTimer);

const updateKeyPosition = (e) => {
  let x = e.clientX;
  let y = e.clientY;
  key.style.left = x - keyBox.width/1.5;
  key.style.top = y - keyBox.height/2;
};

const grantAccess = () => {
  key.parentElement.parentElement.style.cursor = "default";

  heading.textContent = '🎉 yay 🎉';
  paragraph.textContent = 'access granted';

  keyhole.style.display = "none";
  key.style.display = "none";

  window.removeEventListener("mousemove", updateKeyPosition);
  keyhole.removeEventListener("mouseover", grantAccess);
};

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload' %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>

    <body class=''>
      <%= render 'layouts/header' %>
      <div class="max-w-screen-xl mt-10 mx-auto px-4 sm:px-6 lg:px-8">
        <%= yield %>
      </div>
    </body>
</html>

app/views/posts/_comment.html.erb
<div class="my-4 flex items-center">
  <%= image_tag('https://picsum.photos/200/300', class: 'h-12 w-12 mr-4 object-cover border rounded-full', alt: 'avatar') %>
  <div class="">
    <h4 class="text-xl"><%= t(:comment_by) %> <%= comment.user.email %></h4>
    <p class="comment text-md"><%= comment.body %></p>
    <p class="sm:text-sm text-xs tracking-normal text-gray-600"><%= t(:posted) %> <%= distance_of_time_in_words(comment.post.created_at, comment.created_at) %> later</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: 'contents') do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, 'error') %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title, t(:title) %>
    <%= form.text_field :title, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>

  <div class="my-5">
    <%= form.label :content, t(:content) %>
    <%= form.text_area :content, rows: 4, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>

  <div class="my-5">
    <%= form.label :tag_list, t(:tag_list) %>
    <%= form.text_field :tag_list, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full', placeholder: 'ruby, rails, world' %>
  </div>

  <div class="my-5">
    <%= image_tag(post.image_as_thumbnail, class: 'my-10', alt: 'image') %>
    <%= form.file_field :image %>
  </div>

  <div class="inline">
    <%= form.submit class: 'relative py-2.5 px-5 border border-transparent text-md md:text-sm leading-5 text-center font-medium rounded-md text-white bg-green-600 hover:bg-green-500 focus:outline-none focus:border-green-700 focus:shadow-outline-green active:bg-green-700 transition duration-150 ease-in-out' %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>
<% end %>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full mb-10">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Show this post', @post, class: 'relative py-2.5 px-5 border border-transparent border-black text-md md:text-sm leading-5 text-center font-medium rounded-md text-black bg-white hover:bg-gray-200 focus:outline-none focus:border-gray-700 focus:shadow-outline-green active:bg-gray-300 transition duration-150 ease-in-out' %>
  <%= link_to 'Back to posts', posts_path, class: 'relative py-2.5 px-5 border border-transparent border-black text-md md:text-sm leading-5 text-center font-medium rounded-md text-black bg-white hover:bg-gray-200 focus:outline-none focus:border-gray-700 focus:shadow-outline-green active:bg-gray-300 transition duration-150 ease-in-out' %>
</div>

app/views/posts/index.html.erb
<div class="w-full h-auto pb-20">
  <% if @posts.any? %>
    <div class="w-full text-center">
      <h1 class="text-gray-900 font-extrabold text-5xl md:text-4xl pt-8">Блог</h1>
      <p class="text-gray-500 text-2xl md:text-xl font-normal my-5">Здесь представлены разного рода статьи, которые могут быть вам интересны!</p>
      <% if can? :create, Post %>
        <%= link_to t(:add_post), new_post_path, class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded text-white' %>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <%= link_to t(:my_posts), posts_path(user_id: current_user.id), class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded text-white' %>
      <%= link_to t(:all_posts), posts_path, class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded text-white' %>
    <% end %>
    <div class="flex flex-col md:flex-row w-full mt-6 flex-wrap justify-around">
      <% @posts.each do |post| %>
        <div class="bg-white md:w-96 h-auto mt-5 rounded-lg shadow-md overflow-hidden hover:shadow-sm">
          <%= link_to post, action: 'go' do %>
            <div>
              <%= image_tag(post.image_as_thumbnail, class: 'object-center object-cover w-full h-48', alt: 'image') %>
            </div>
            <div class="px-6 text-left pt-6">
              <h1 class="text-sm md:text-base text-gray-600 font-semibold text-center mb-5"><%= post.title %></h1>
              <p class="text-sm text-gray-500 leading-6 text-left md:h-40 h-auto"><%= strip_tags(post.content).truncate(170) %></p>
            </div>
            <p class="mt-5 ml-6"> <%= t(:tags) %>:
              <% post.tags.each do |tag| %>
                <%= link_to tag.name, tag_path(tag), class: 'bg-gray-200 rounded-xl p-2 italic' %>
              <% end %>
            </p>
          <% end %>
          <div class="flex items-center px-4 mb-3 md:mt-5 mt-10 align-content">
            <div class="h-full">
              <p class="sm:text-sm text-xs tracking-normal text-gray-600 ml-2"><%= post.created_at.strftime('%-d.%m.%Y, %H:%M') %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="w-full text-center pt-8">
      <h1 class="text-gray-900 font-extrabold text-5xl md:text-4xl">Блог</h1>
      <p class="text-gray-500 text-2xl md:text-xl font-normal my-10">Здесь пока нет статей, но скоро они появятся. Вы можете быть первым!</p>
      <% if can? :create, Post %>
        <%= link_to t(:add_post), new_post_path, class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded text-white' %>
      <% end %>
    </div>
  <% end %>
</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back to posts', posts_path, class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
</div>

app/views/posts/show.html.erb
<div class="w-full mx-auto">
  <h2 class="text-center text-gray-900 text-4xl md:text-3xl font-bold tracking-wide"><%= @post.title %></h2>
  <p class="text-justify mt-5 text-gray-600 text-xl md:text-lg tracking-wide leading-8"><%= @post.content %></p>
  <%= image_tag(@post.image_as_thumbnail, class: 'mt-10', alt: 'image') %>
</div>

<div class="flex sm:flex-row sm:justify-between flex-col py-10">
  <div>
    <p class="text-gray-900 sm:text-left text-right font-medium text-sm md:text-sm tracking-wide leading-8"> <%= t(:added) %>: <%= @post.created_at.strftime('%-d.%m.%Y, %H:%M') %></p>
    <p class="text-gray-900 sm:text-left text-right mb-5 sm:mb-0 font-medium text-sm md:text-sm tracking-wide leading-8"><%= t(:updated) %>: <%= @post.updated_at.strftime('%-d.%m.%Y, %H:%M') %></p>
  </div>

  <div class="flex sm:flex-row py-3 flex-col items-end">
    <% if can? :update, @post %>
      <div>
        <%= link_to t(:edit), edit_post_path(@post), class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded' %>
      </div>
    <% end %>
    <% if can? :destroy, @post %>
      <div class="sm:mx-5 mt-5 sm:mt-0">
        <%= link_to t(:delete), @post, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded', method: :delete, data: { confirm: 'Вы уверены, что хотите удалить статью?' } %>
      </div>
    <% end %>
  </div>

</div>

<h3 class="mb-3"><%= t(:comments) %> (<%= @post.comments.size %>)</h3>
<%= render partial: 'posts/comment', collection: @post.comments.reverse %>
<% if user_signed_in? %>
  <%= render partial: 'comments/form' %>
<% end %>

app/views/tags/show.html.erb
<h1 class="text-xl">Post Tagged with <%= @tag.name %></h1>

<div class="grid xl:grid-cols-3 grid-cols-2">
  <% @tag.posts.each do |post| %>
    <div class="bg-white md:w-96 h-auto mt-5 rounded-lg shadow-md overflow-hidden hover:shadow-sm">
      <%= link_to post, action: 'go' do %>
        <div>
          <%= image_tag(post.image_as_thumbnail, class: 'object-center object-cover w-full h-48', alt: 'image') %>
        </div>
        <div class="px-6 text-left pt-6">
          <h1 class="text-sm md:text-base text-gray-600 font-semibold text-center mb-5"><%= post.title %></h1>
          <p class="text-sm text-gray-500 leading-6 text-left md:h-40 h-auto"><%= strip_tags(post.content).truncate(170) %></p>
        </div>
      <% end %>
      <div class="flex items-center px-4 mb-3 md:mt-5 mt-10 align-content">
        <div class="h-full">
          <p class="sm:text-sm text-xs tracking-normal text-gray-600 ml-2"><%= post.created_at.strftime('%-d.%m.%Y, %H:%M') %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>